credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "git_visionaryops"
              password: "{AQAAABAAAAAwVeUAvNhQzZbgRSeJK1GiNyjRh9Tr1zkwA/A76LPApoRKfqNCF0BcueDs/KC0yK24+EYMY4YxUI+jwCDquy5lkw==}"
              scope: GLOBAL
              username: "NOUR-BEN -ALI"
          - usernamePassword:
              id: "docker_visionaryops"
              password: "{AQAAABAAAAAwPZshDOqGW2uk9gffDhNxN0IiMAPf2pXZhNO4Bv44oQjBkqxMlhzaTtOzhTddLWCp5eiohSe2ujhYznEsRSTHUg==}"
              scope: GLOBAL
              username: "nourbenali"
          - usernamePassword:
              id: "git-cred"
              password: "{AQAAABAAAAAwOo/BPF2+zLJa2dhs2TUo36gFpeuyNNO9Tw+Yb5d7VJ8mhmwZz97QHTTsVG4Tc8X7J2+baK65fkif6lBZoc+JSQ==}"
              scope: GLOBAL
              username: "NOUR-BEN-ALI"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
    - "architecture"
    - "clock"
    - diskSpace:
        freeSpaceThreshold: "1GiB"
        freeSpaceWarningThreshold: "2GiB"
    - "swapSpace"
    - tmpSpace:
        freeSpaceThreshold: "1GiB"
        freeSpaceWarningThreshold: "2GiB"
    - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "admin"
          properties:
            - "consoleUrlProvider"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "theme"
            - "timezone"
            - "experimentalFlags"
            - mailer:
                emailAddress: "nour.benali@esprit.tn"
            - "apiToken"
  slaveAgentPort: 50000
  systemMessage: "Jenkins configured automatically by CasC"
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  globalTimeOutConfiguration:
    operations:
      - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  kafka:
    enableSSL: false
    kubernetesSkipTlsVerify: false
    useKubernetes: false
  location:
    adminAddress: "l'adresse n'est pas encore configurée <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  dockerTool:
    installations:
      - home: "/usr/bin"
        name: "docker"
  git:
    installations:
      - home: "git"
        name: "Default"
  jdk:
    installations:
      - home: "/usr/local/jdk-21.0.4"
        name: "jdk"
  maven:
    installations:
      - home: "/opt/apache-maven-4.0.0-beta-3"
        name: "maven"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  pipelineMaven:
    daoClass: "org.jenkinsci.plugins.pipeline.maven.db.PipelineMavenPluginPostgreSqlDao"
    globalTraceability: false
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false