apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication-microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapplication-microservice1
  template:
    metadata:
      labels:
        app: myapplication-microservice1
    spec:
      containers:
        - name: myapplication-microservice1
          image: nourbenali/myapplication-microservice1:latest
          ports:
            - containerPort: 9989
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/basepfe3"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9093"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data  # Adjust the path if necessary
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data  # Assuming you've created a PersistentVolumeClaim for this purpose
