version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI port
    environment:
      # Configuration Jaeger pour le stockage OTLP
      STORAGE_TYPE: otlp
      OTLP_ENDPOINT: http://jaeger-collector:14268

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    ports:
      - "14268:14268"

  Microservice1:
    build: ./microservice1
    command: ["java", "-javaagent:/app/libs/./opentelemetry-javaagent.jar", "-jar", "Microservice1-0.0.1-SNAPSHOT.jar
"]
    ports:
      - "8093:8093"

#  Microservice2:
#    build: ./microservice2  # Exemple de chemin de construction
#    command: ["java", "-javaagent:/app/libs/opentelemetry-javaagent.jar", "-jar", "myapp.jar"]
#    ports:
#      - "8094:8094"
#
#  Microservice3:
#    build: ./microservice3  # Exemple de chemin de construction
#    command: ["java", "-javaagent:/app/libs/opentelemetry-javaagent.jar", "-jar", "myapp.jar"]
#    ports:
#      - "8095:8095"

volumes:
  jaeger-storage: