#receivers:
#  otlp:
#    protocols:
#      grpc:
#      http:
#
#processors:
#  batch:
#
#exporters:
#  logging:
#  loki:
#    endpoint: http://loki:3100/loki/api/v1/push
#
#service:
#  pipelines:
#    logs:  # Pipeline for log data
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging, loki]
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]