{
 "title": "Tempo Traces",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Microservice1-traces",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_spanmetrics_duration_seconds_sum",
     "filters": [
      { "id": "d5557b36", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Microservice1" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "basepfe3",
        "SELECT basepfe3"
       ],
       "valueType": "string"
      }
     ],
     "legendFormat": "{{trace_name}} - {{service_name}}",
     "limit": 20
    }
   ]
  },
  {
   "title": "Microservice3-traces",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_trace_count_total",
     "filters": [
      { "id": "c5193b89", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Microservice3" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "SELECT basepfe4",
        "SELECT basepfe5"
       ],
       "valueType": "string"
      }
     ],
     "legendFormat": "{{trace_name}} - {{service_name}}",
     "limit": 20
    }
   ]
  },
  {
   "title": "Microservice2-traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "tempo_spanmetrics_errors_total / tempo_spanmetrics_started_total * 100",
     "filters": [
      {
       "id": "fb653cf1",
       "operator": "=",
       "scope": "span",
       "tag": "status",
       "value": [ "unset" ],
       "valueType": "keyword"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Microservice2" ],
       "valueType": "string"
      }
     ],
     "legendFormat": "{{trace_name}} - {{service_name}}",
     "limit": 20
    }
   ]
  }
 ]
}