# Use an OpenJDK base image
FROM openjdk:23-slim-bullseye
# Copy the JAR file from your project into the container
COPY target/microservice2.jar /app/microservice2.jar
# Expose the port your Spring Boot application runs on (change to the actual port)

EXPOSE 9988
# Define the command to run your Spring Boot application
CMD ["java", "-jar", "/app/microservice2.jar"]
